package app.vessel.data

import android.app.WallpaperManager
import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Canvas
import android.graphics.Matrix
import android.graphics.Paint
import android.graphics.drawable.BitmapDrawable
import android.graphics.drawable.Drawable
import android.net.Uri
import android.os.ParcelFileDescriptor
import app.vessel.core.DesktopBackground
import app.vessel.core.DisplayGeometry
import app.vessel.core.VESSEL_DESKTOP_COLOR
import app.vessel.core.WallpaperOrigin
import app.vessel.core.dominantColor
import app.vessel.core.encodeBmp24
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import javax.inject.Inject
import javax.inject.Singleton
import kotlin.math.max

/**
 * The phone's home-screen wallpaper, turned into something Wine's desktop can
 * paint.
 *
 * ## Why this probes five APIs instead of calling one
 *
 * Which `WallpaperManager` entry point returns the *user's* wallpaper is a
 * per-device, per-`targetSdk` question with no answer in the documentation.
 * `getDrawable()` has needed `READ_EXTERNAL_STORAGE` since API 24, that
 * permission has been progressively defanged since API 33, and on some releases
 * a restricted caller is handed the **stock** wallpaper rather than a
 * `SecurityException` — which is the worst outcome available, because it looks
 * like success. So every entry point is called, every answer is recorded, and
 * the record goes into the session log as [DesktopBackground.attempts]. What
 * this class reports is what the device did, not what the API reference says it
 * should do.
 *
 * ## The three tiers, and never a substitute for a higher one
 *
 * 1. the phone's wallpaper, 2. a still the user dropped in the container
 * directory, 3. a flat colour. A live wallpaper has no still frame at all —
 * `wallpaperInfo != null` means the pixels are being generated by a service, and
 * anything `getDrawable()` hands back in that state is a leftover or a default
 * and is not what is on the home screen. That case degrades rather than
 * pretending, and [DesktopBackground.summary] says which tier was reached.
 *
 * Even tier 3 is derived rather than invented where it can be:
 * `getWallpaperColors(FLAG_SYSTEM)` needs no permission and works for live
 * wallpapers, because it is what Material You colour extraction runs on.
 */
@Singleton
class AndroidWallpaper @Inject constructor(
    @ApplicationContext private val context: Context,
) {

    /**
     * Resolve the background for one session and write the bitmap into [layout].
     *
     * Re-run on every session start rather than cached: the wallpaper can change
     * between launches, and the derived file is cheap next to the rest of
     * Preparing. It is deliberately *not* pushed into a running desktop — Wine
     * repaints on `WM_SETTINGCHANGE`, and there is nothing on the guest side that
     * can send one (`WinHandler` is still an interface with a no-op
     * implementation), so a wallpaper changed mid-session lands at the next start.
     */
    suspend fun derive(
        layout: ContainerLayout,
        geometry: DisplayGeometry,
    ): DesktopBackground = withContext(Dispatchers.IO) {
        val attempts = mutableListOf<String>()
        val manager = runCatching { WallpaperManager.getInstance(context) }.getOrElse {
            attempts += "WallpaperManager.getInstance() -> ${describe(it)}"
            return@withContext colorOnly(layout, null, attempts, "no WallpaperManager on this device")
        }

        val live = runCatching { manager.wallpaperInfo }.getOrNull()
        if (live != null) {
            // Not a failure and not something to work around: a live wallpaper is
            // a running service, and there is no frame of it to read. Saying so is
            // the whole point — substituting the still the user had before they
            // set it would be a picture nobody currently sees.
            attempts += "wallpaperInfo -> live wallpaper ${live.packageName}/${live.serviceName}"
            return@withContext fromOverrideOrColor(
                manager = manager,
                layout = layout,
                geometry = geometry,
                attempts = attempts,
                why = "the home screen runs the live wallpaper ${live.loadLabel(context.packageManager)}, " +
                    "which has no still frame to copy",
            )
        }
        attempts += "wallpaperInfo -> null (a static wallpaper is set)"

        val source = firstUsable(manager, attempts)
        if (source == null) {
            return@withContext fromOverrideOrColor(
                manager = manager,
                layout = layout,
                geometry = geometry,
                attempts = attempts,
                why = "no WallpaperManager call returned the wallpaper to this app",
            )
        }

        val pixels = fit(source.bitmap, geometry)
        source.bitmap.recycle()

        // The one check that separates "we read your wallpaper" from "the system
        // handed us the factory image and said nothing". A match is not proof of
        // either — the user may simply be running the stock wallpaper — so it is
        // reported rather than acted on.
        val stock = builtIn(manager, geometry, attempts)
        val indistinguishable = stock != null && stock.contentEquals(pixels)

        val written = write(layout, geometry, pixels, attempts)
        if (!written) {
            return@withContext colorOnly(
                layout = layout,
                color = dominantColor(pixels),
                attempts = attempts,
                why = "the wallpaper was read but could not be written into the prefix",
            )
        }

        DesktopBackground(
            origin = WallpaperOrigin.SYSTEM_WALLPAPER,
            color = dominantColor(pixels),
            summary = buildString {
                append("Home-screen wallpaper via ${source.api}, at $geometry")
                if (indistinguishable) {
                    append(" — identical to the built-in default, so this is either ")
                    append("the stock wallpaper or the system substituted it")
                }
            },
            attempts = attempts,
        )
    }

    // — tier 1: the phone's own wallpaper ---------------------------------------

    /** One API that answered with a bitmap. */
    private class Source(val api: String, val bitmap: Bitmap)

    /**
     * Every entry point in turn, stopping at the first that yields pixels.
     *
     * `getWallpaperFile` is last of the four despite being the most direct: it
     * hands back a descriptor for the file on disk, so when it works it is the
     * best answer, but it is also the one most likely to be refused outright, and
     * the ordering here is the one the report is expected in.
     */
    @Suppress("DEPRECATION")
    private fun firstUsable(manager: WallpaperManager, attempts: MutableList<String>): Source? {
        // The three drawable getters are deprecated and are still the ones that
        // work on some releases; leaving them out would put a hole in the report.
        val probes = listOf<Pair<String, () -> Bitmap?>>(
            "getDrawable()" to { toBitmap(manager.drawable) },
            "getFastDrawable()" to { toBitmap(manager.fastDrawable) },
            "peekDrawable()" to { toBitmap(manager.peekDrawable()) },
            "getWallpaperFile(FLAG_SYSTEM)" to { decode(manager.getWallpaperFile(WallpaperManager.FLAG_SYSTEM)) },
        )
        for ((api, call) in probes) {
            val bitmap = runCatching(call).fold(
                onSuccess = { it },
                onFailure = {
                    // SecurityException is the documented refusal and is caught
                    // here with everything else on purpose: a probe that throws
                    // anything at all is a probe that did not work, and the type
                    // is in the record for whoever reads it.
                    attempts += "$api -> ${describe(it)}"
                    null
                },
            )
            if (bitmap == null) {
                if (attempts.none { it.startsWith(api) }) attempts += "$api -> null"
                continue
            }
            attempts += "$api -> ${bitmap.width}x${bitmap.height} ${bitmap.config}"
            return Source(api, bitmap)
        }
        return null
    }

    /**
     * The factory wallpaper, scaled the same way, purely as a comparator.
     *
     * Never used as the background. It is not the user's wallpaper by definition,
     * and drawing it while calling it theirs is exactly the fabrication this file
     * is built to avoid.
     */
    @Suppress("DEPRECATION")
    private fun builtIn(
        manager: WallpaperManager,
        geometry: DisplayGeometry,
        attempts: MutableList<String>,
    ): IntArray? = runCatching {
        val bitmap = toBitmap(manager.builtInDrawable) ?: return@runCatching null
        attempts += "getBuiltInDrawable() -> ${bitmap.width}x${bitmap.height} (comparator only)"
        fit(bitmap, geometry).also { bitmap.recycle() }
    }.getOrElse {
        attempts += "getBuiltInDrawable() -> ${describe(it)}"
        null
    }

    // — tiers 2 and 3 ------------------------------------------------------------

    /** A user-supplied still if there is one, otherwise the flat colour. */
    private fun fromOverrideOrColor(
        manager: WallpaperManager,
        layout: ContainerLayout,
        geometry: DisplayGeometry,
        attempts: MutableList<String>,
        why: String,
    ): DesktopBackground {
        val file = layout.wallpaperOverrides.firstOrNull { it.isFile }
        if (file == null) {
            attempts += "container override -> none of ${layout.wallpaperOverrides.joinToString(", ") { it.name }}"
            return colorOnly(layout, wallpaperColor(manager, attempts), attempts, why)
        }

        val decoded = runCatching { BitmapFactory.decodeFile(file.absolutePath) }.getOrNull()
        if (decoded == null) {
            attempts += "container override -> ${file.name} is not a readable image"
            return colorOnly(layout, wallpaperColor(manager, attempts), attempts, why)
        }
        attempts += "container override -> ${file.name} ${decoded.width}x${decoded.height}"

        val pixels = fit(decoded, geometry)
        decoded.recycle()
        if (!write(layout, geometry, pixels, attempts)) {
            return colorOnly(layout, dominantColor(pixels), attempts, why)
        }
        return DesktopBackground(
            origin = WallpaperOrigin.USER_IMAGE,
            color = dominantColor(pixels),
            summary = "${file.name} from the container directory, because $why",
            attempts = attempts,
        )
    }

    /**
     * No image at all. Removes any bitmap a previous session wrote, so the desktop
     * cannot go on showing a wallpaper the phone no longer has.
     *
     * **The colour is Vessel's own dark ground, not the wallpaper's dominant
     * hue**, and that reverses an earlier decision worth recording. Extracting the
     * hue was the more faithful thing to do and it looked broken: this phone's
     * wallpaper extracts to `#4AD107`, so the Windows desktop came up a flat
     * fluorescent green behind a dark file manager, which reads as a rendering
     * bug rather than as a deliberate fallback. Wine's own `RGB(58, 110, 165)` had
     * the same problem in blue. The extracted colour still goes into [attempts],
     * where it is evidence rather than paint.
     */
    private fun colorOnly(
        layout: ContainerLayout,
        color: Int?,
        attempts: MutableList<String>,
        why: String,
    ): DesktopBackground {
        runCatching { layout.wallpaper.delete() }
        return DesktopBackground(
            origin = WallpaperOrigin.DESKTOP_COLOR,
            color = VESSEL_DESKTOP_COLOR,
            // One plain sentence, and it has to name the fix rather than the
            // failure: "Android denied a permission" is not something a user can
            // act on, and picking an image is.
            summary = "$why, so the desktop is Vessel's own dark background. Pick an image to use one.",
            attempts = attempts,
        )
    }

    // — the user's own image -------------------------------------------------------

    /**
     * Copy [source] into the container as the wallpaper for this and every later
     * session.
     *
     * Fed from Android's photo picker, which is the only route that is both
     * honest and permissionless: `PickVisualMedia` hands back a `content://` URI
     * the user selected, and reading it needs no manifest permission at all on
     * any API level. `MANAGE_EXTERNAL_STORAGE` would technically unblock
     * `getDrawable()` and is not on the table — it is an all-files grant asked
     * for to draw a background.
     *
     * The bytes are copied rather than the URI remembered. A `content://` grant
     * from a picker lasts as long as the process that received it, and a
     * wallpaper that vanishes on the next cold start is worse than none.
     */
    suspend fun adopt(layout: ContainerLayout, source: Uri): Boolean = withContext(Dispatchers.IO) {
        runCatching {
            clear(layout)
            val target = layout.wallpaperOverrides.first()
            target.parentFile?.mkdirs()
            context.contentResolver.openInputStream(source)!!.use { input ->
                target.outputStream().use(input::copyTo)
            }
            // Decodable, or it is not a wallpaper. Failing here beats writing a
            // file that silently produces a flat colour two screens later.
            BitmapFactory.decodeFile(target.absolutePath) != null || run {
                target.delete()
                false
            }
        }.getOrDefault(false)
    }

    /** Forget a picked image, so the next session goes back to the phone's own. */
    suspend fun clear(layout: ContainerLayout) = withContext(Dispatchers.IO) {
        layout.wallpaperOverrides.forEach { runCatching { it.delete() } }
        Unit
    }

    /**
     * The wallpaper's primary colour, which needs no permission and survives a
     * live wallpaper.
     *
     * This is the same extraction Material You runs on, so it is a real property
     * of what is on the home screen rather than a stand-in for one. Null when even
     * that is refused, which is the only case that reaches
     * [VESSEL_DESKTOP_COLOR].
     */
    private fun wallpaperColor(manager: WallpaperManager, attempts: MutableList<String>): Int? =
        runCatching {
            val colors = manager.getWallpaperColors(WallpaperManager.FLAG_SYSTEM)
            if (colors == null) {
                attempts += "getWallpaperColors(FLAG_SYSTEM) -> null"
                return@runCatching null
            }
            colors.primaryColor.toArgb().also {
                attempts += "getWallpaperColors(FLAG_SYSTEM) -> primary #%06X".format(it and 0xFFFFFF)
            }
        }.getOrElse {
            attempts += "getWallpaperColors(FLAG_SYSTEM) -> ${describe(it)}"
            null
        }

    // — pixels -------------------------------------------------------------------

    /**
     * [source] centre-cropped and scaled to exactly [geometry].
     *
     * Exactly, because Wine centres the wallpaper at its own size and never
     * scales it: one pixel short in either axis and `PaintDesktop` fills the whole
     * rectangle with `COLOR_BACKGROUND` first and then drops the image into the
     * middle of it. Centre-crop rather than letterbox for the same reason — a
     * portrait phone wallpaper on a landscape desktop would otherwise be a strip
     * of picture between two bars.
     */
    private fun fit(source: Bitmap, geometry: DisplayGeometry): IntArray {
        val out = Bitmap.createBitmap(geometry.width, geometry.height, Bitmap.Config.ARGB_8888)
        val scale = max(
            geometry.width.toFloat() / source.width,
            geometry.height.toFloat() / source.height,
        )
        val matrix = Matrix().apply {
            setScale(scale, scale)
            postTranslate(
                (geometry.width - source.width * scale) / 2f,
                (geometry.height - source.height * scale) / 2f,
            )
        }
        Canvas(out).drawBitmap(source, matrix, Paint(Paint.FILTER_BITMAP_FLAG))

        val pixels = IntArray(geometry.width * geometry.height)
        out.getPixels(pixels, 0, geometry.width, 0, 0, geometry.width, geometry.height)
        out.recycle()
        return pixels
    }

    private fun write(
        layout: ContainerLayout,
        geometry: DisplayGeometry,
        pixels: IntArray,
        attempts: MutableList<String>,
    ): Boolean = runCatching {
        val target = layout.wallpaper
        // The prefix's `drive_c` does not exist until wineboot has run, and this
        // step is deliberately ahead of it — the directories are ours to create,
        // the same way the FEX payload's system32 is.
        target.parentFile?.mkdirs()
        target.writeBytes(encodeBmp24(geometry.width, geometry.height, pixels))
        attempts += "wrote ${target.name} (${target.length()} bytes, 24-bit BMP)"
        true
    }.getOrElse {
        attempts += "writing ${layout.wallpaper.name} -> ${describe(it)}"
        false
    }

    private fun decode(descriptor: ParcelFileDescriptor?): Bitmap? =
        descriptor?.use { BitmapFactory.decodeFileDescriptor(it.fileDescriptor) }

    private fun toBitmap(drawable: Drawable?): Bitmap? {
        if (drawable == null) return null
        (drawable as? BitmapDrawable)?.bitmap?.let { return it }
        val width = drawable.intrinsicWidth
        val height = drawable.intrinsicHeight
        if (width <= 0 || height <= 0) return null
        val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
        drawable.setBounds(0, 0, width, height)
        drawable.draw(Canvas(bitmap))
        return bitmap
    }

    private fun describe(error: Throwable): String =
        "${error.javaClass.simpleName}: ${error.message ?: "no message"}"
}
